### ISSUE TITLE
Hangs or returns 502 bad gateway error

### ISSUE THREAD

**Issue by wphowell** [osmium-org/osmium#199]
The site seems very unreliable these days, with lots of 502 errors and/or timeouts; or the following error:

Could not sync loadout with remote: error (). This shouldn't normally happen, try again or refresh the page. Please report if the problem persists.

**Comment by Landshrew** [comment]
I have been getting a lot of these today too.

**Comment by Artefact2** [comment]
On Mon, Nov 06, 2017 at 10:35:23PM +0000, Landshrew wrote:
> I have been getting a lot of these today too.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/osmium-org/osmium/issues/199#issuecomment-342311102

I fixed an issue today in the cache pruning script, it turns out
sessions hadn't been cleared for quite some time. The cache directory
contained 2.2 million files, 95% of which were useless. No filesystem,
no matter how good, handles a single directory with so many files
well, which may explain the frequent timeouts, especially today as it
took a lot of I/O to remove all the stale files.

Please tell me if the issue keeps happening from now on in the next
couple of days.

**Comment by wphowell** [comment]
Seems to be operating perfectly now -- very responsive!

**Comment by Artefact2** [comment]
This might just be placebo effect. Don't hesitate to repoen in a few days if you still encounter many timeouts.
